schema-version = "1.10.0"

[include]
  [[include.environments]]
    dir = '/var/lib/git/nxmatic/fleet/flox/keyhole'

[install]
html2text.pkg-path = "html2text"
html2text.outputs = "all"
zgrviewer.pkg-path = "zgrviewer"
  [install.antora]
    pkg-group = "asciidoc"
    pkg-path = "antora"
outputs = "all"

  [install.antora-lunr-extension]
    pkg-group = "asciidoc"
    pkg-path = "antora-lunr-extension"
outputs = "all"

  [install.antora-ui-default]
    pkg-group = "asciidoc"
    pkg-path = "antora-ui-default"
outputs = "all"

  [install.asciidoctor-with-extensions]
    pkg-group = "asciidoc"
    pkg-path = "asciidoctor-with-extensions"
outputs = "all"

  [install.graphviz]
    pkg-group = "asciidoc"
    pkg-path = "graphviz"
outputs = "all"

  [install.jdk]
    pkg-group = "asciidoc"
    pkg-path = "jdk"
outputs = "all"

  [install.nodejs]
    pkg-group = "asciidoc"
    pkg-path = "nodejs"
outputs = "all"

  [install.plantuml]
    pkg-group = "asciidoc"
    pkg-path = "plantuml"
outputs = "all"

  [install.pnpm]
    pkg-group = "asciidoc"
    pkg-path = "pnpm"
outputs = "all"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux", "x86_64-darwin"]

[profile]
  common = """
    export ANTORA_CACHE_DIR="${FLOX_ENV_PROJECT}/.cache/antora"
    export DOCS_BUILD_DIR="${FLOX_ENV_PROJECT}/.output/docs"
  """
