schema-version = "1.11.0"

[include]
  [[include.environments]]
    dir = '/var/lib/git/nxmatic/fleet/flox/xdg'

  [[include.environments]]
    dir = '/var/lib/git/nxmatic/fleet/flox/keyhole'

[install]
  [install.direnv]
    pkg-group = "home"
    pkg-path = "direnv"
outputs = "all"

  [install.lldpd]
    pkg-group = "home"
    pkg-path = "lldpd"
outputs = "all"

[options]
  systems = ['aarch64-darwin', 'aarch64-linux']
